{% set name = "datalad" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48f19d3e4fc7b2725240e6c47d6710f3bc46ad6b42455ff76dd3f6e34226f39f
  patches:
    - annexremote_linux.patch

build:
  number: 0
  entry_points:
    - datalad = datalad.cli.main:main
    - git-annex-remote-datalad-archives = datalad.customremotes.archives:main
    - git-annex-remote-datalad = datalad.customremotes.datalad:main
    - git-annex-remote-ria = datalad.customremotes.ria_remote:main
    - git-annex-remote-ora = datalad.distributed.ora_remote:main
    - git-credential-datalad = datalad.local.gitcredential_datalad:git_credential_datalad
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - packaging
    - setuptools >=59.0.0
    - fasteners
    - looseversion
    # The ones below are not listed in the metadata!
    - pypandoc
  run:
    - python >={{ python_min }}
    - platformdirs
    - chardet >=3.0.4
    - colorama  # [win]
    - distro
    - iso8601
    - humanize
    - fasteners >=0.14
    - packaging
    - patool >=1.7
    - tqdm >=4.32.0
    # NB: remove typing-extensions when droppping py310!
    - typing-extensions >=4.0.0
    - annexremote  # [linux]
    - looseversion
    - boto3
    - keyring >=20.0,!=23.9.0
    - keyrings.alt
    - msgpack-python
    - requests >=1.2
    - python-gitlab
    # The ones below are not listed in the metadata!
    - 7zip  # [win]
    - exifread
    - git  # [not win]
    - git-annex  # [linux]
    - mutagen >=1.36  # [not win]
    - p7zip  # [not win]
    - pillow  # [not win]
    - psutil
    - pyperclip  # [not win]
    - python-dateutil
    - requests-ftp
    - secretstorage  # [linux]
    - setuptools
    - simplejson
    - whoosh
    # TODO
    # - python-xmp-toolkit
    # OS-noarch
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - datalad
  commands:
    - pip check
    - datalad --help
    - git-annex-remote-datalad-archives --help
    - git-annex-remote-datalad --help
    - git-annex-remote-ria --help
    - git-annex-remote-ora --help
    - git-credential-datalad --help
  requires:
    - python {{ python_min }}
    - pip
    # The ones below are not listed in the metadata!
    - BeautifulSoup4
    - httpretty >=0.8.14
    - mock
    - nibabel
    - nose
    - pytest
    - pytest-fail-slow
    - packaging
    - vcrpy
  source_files:
    - tox.ini

about:
  home: https://datalad.org
  license: MIT
  license_file: COPYING
  summary: Distributed system for joint management of code, data, and their relationship
  description: |
    DataLad's purpose is to make data management and data distribution more accessible.
    To do so, it stands on the shoulders of Git and Git-annex to deliver a decentralized
    system for data exchange. This includes automated ingestion of data from online portals and
    exposing it in readily usable form as Git(-annex) repositories - or datasets. However,
    the actual data storage and permission management remains with the original data provider(s).
  doc_url: https://datalad.readthedocs.io/
  dev_url: https://github.com/datalad/datalad

extra:
  recipe-maintainers:
    - yarikoptic
    - notestaff
    - mih
